# to set an integer to a variable, L needs to be appendede after the number
i=5L
is.integer(i)
is.numeric(i)
# if L is not appended
j=5
is.integer(j)
# R promotes integer to numeric when performing multiplication or division

# About "factor" function
mons = c("March","April","January","November","January","September","October",
         "September","November","August","January","November","November",
         "February","May","August","July","December","August","August",
         "September","November","February","April")
mons

# factorize vector "mons"
fmons=factor(mons,levels=c("January","February","March","April","May","June","July",
                     "August","September","October","November","December"),
       ordered=TRUE)
fmons
# replacing character strings with numbers to cloned new vector "fnmons"
# fnmons means factorized and numerified "mons" vector
fnmons=fmons
levels(fnmons)=c(1:12)
fnmons
table(fnmons)
# calculation of average of "fnmons" needs to convert it back to numerics
mean(as.numeric(fnmons))
# or
mean(as.numeric(levels(fnmons)[fnmons]))
# levels(fnmons)[fnmons] is basically the original "fnmons" vector


# find length of a character or a numeric
nchar("hello")
nchar("good")
nchar("168")
nchar("1865")
# but nchar function can't be used on factor
f=factor(1:8)
nchar(f)  
# nchar(f) will report error

# about date
date1<-c("2007/06/22", "2004/02/13")
date1[1]-date1[2]
# the above operation will report error cuz characters needs to be converted
cdate1<-as.Date(date1,"%Y/%m/%d")
cdate1[1]-cdate1[2]
# when converting, requested format "%Y/%m/%d" should be consistent with vector 'date1'
date2 <- c("1jan1960", "2jan1960", "31mar1960", "30jul1960")
cdate2<- as.Date(date2,"%d%b%Y")
cdate2
# %A%a <-> Monday Mon; %B%b <-> February Feb
date3<- as.POSIXct("2012-06-28 17:42")
date3
class(date3)
as.numeric(date3)
# when numerified, date+time generated by as.POSIXct is in seco

# about 'lubridate'
meetingNZ <- ymd_hms("2011-07-01 09:00:00", tz = "Pacific/Auckland")
meetingNZ
meetingUS<-with_tz(meeting, "America/Chicago")
# my colleague mistook it as the time in his time zone
mistake <- force_tz(meetingNZ, "America/Chicago")
mistake
# force_tz just change the time zone but with same date and time
# with_tz checks corresponding date and time in another time zone
# so when he calls, my time at New Zealand is
UScall<-with_tz(mistake, tzone= "Pacific/Auckland")
# 'tzone=' can be neglected
# actual time gap
UScall-meeting
# he calls 17 hours later than the due time











